input {
  file {
    path => "/data/movies.csv"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => plain { charset => "UTF-8" }
  }
}

filter {
  csv {
    separator => ","
    quote_char => '"'
    columns => [
      "id", "title", "genres", "original_language", "overview",
      "popularity", "production_companies", "release_date", "budget",
      "revenue", "runtime", "status", "tagline", "vote_average",
      "vote_count", "credits", "keywords", "poster_path",
      "backdrop_path", "recommendations"
    ]
  }

  # Supprime la ligne de header
  if [id] == "id" {
    drop {}
  }

  # Supprime les champs internes Logstash
  mutate {
    remove_field => ["@version", "host", "log", "message", "event"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "movies_raw"
  }
}